### ISSUE TITLE
npm run build fails - missing jackage.json

### ISSUE THREAD

**Issue by rssfed23** [chmille4/bam.iobio.io#125]
After cloning the repository and running npm run build I get an error
```
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! path /home/rob/bam.iobio.io/package.json
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall open

npm ERR! enoent ENOENT: no such file or directory, open '/home/rob/bam.iobio.io/package.json'
npm ERR! enoent ENOENT: no such file or directory, open '/home/rob/bam.iobio.io/package.json'
npm ERR! enoent This is most likely not a problem with npm itself
npm ERR! enoent and is related to npm not being able to find a file.
```

Are there instructions on how this can be run/built locally?

**Comment by rssfed23** [comment]
Never mind - noob issue didn't run npm install first *facepalm*

**Comment by anderspitman** [comment]
@rssfed23 just to make sure, you're using the gh-pages branch, right? That's currently our primary branch, which we should probably change.

**Comment by rssfed23** [comment]
@anderspitman yeah I didn't notice it was gh-pages as the default branch at first. Switched to master and all my problems went away :)

Great app btw! - It's helped countless people in a private facebook group I'm in (Dante Labs Customers) figure out the rough quality of their BAMs. As direct to consumer NGS WGS becomes more popular easy to use tools like this are in high demand!

**Comment by anderspitman** [comment]
gh-pages is actually the one you want. The code in master is deprecated and will likely stop working in the not-to-distant future. I'm happy to explain more if necessary.

So Dante does actually send BAMs to people? I've been waiting for mine since last November.

**Comment by rssfed23** [comment]
@anderspitman part of the demo I was using this for involved compiling it in node (on a cloudfoundry environment) so switching worked in my favour. Although behind the scenes I did have the gh-pages one up just incase!

Yep they do! Since they opened their new lab in Italy anyway. They've recalled all the samples from BGI and are sequencing them themselves now. I ordered in July and got my results 3 weeks ago. New customers are getting them in about 6 weeks.
Oh also the BAM/FASTQs are available for download no need to order a HD from them anymore.
Don't get me wrong; they still have a fair way to go (initial samples from the new lab were well below 30x across most of the exome so they're tweaking things ) but they're definitely better than they were. If you've not logged into their genome manager in a while take a look and you may get a surprise.
Alternatively join the facebook group there's a couple of their support people on there occasionally answering peoples queries: https://www.facebook.com/groups/373644229897409/
You'll see this tool posted quite a few times as there's a lot of people new to bioinformatics in there getting help on interpreting their results.

Personally they're resequencing my 2 samples due to low coverage. Having said that; my "second sample" was actually sent in error by them and they've never noticed so I've had 2 sequences for the price of one and the merged fastq makes up for the lack of coverage. If they do resequence both of them like they've said they will then I'll have even more coverage!

**Comment by anderspitman** [comment]
Not sure exactly what you mean but it sounds like you got it to work for what you needed. Let me know if you run into any problems.

Thanks for the Dante info. I'll join the group. I've been checking the dashboard and emailing them fairly regularly. The whole situation, including your information, really doesn't inspire much confidence in the final data.

**Comment by rssfed23** [comment]
Yeah you really have to validate the data once you get it. Anyone without some basic bioinformatics skills is really being left in the dark by them. Their reports are even more useless than when you purchased them as they no longer use sequencing.com for it.

I guess it depends on the reason for sequencing. Many in the group only want the BAMs for Genealogy but then find out they're getting 6x on Y. Very fustrating for everyone. Personally I went in it for medical so happy with my data (thanks to their incompetence) but most people are not.

There's another DTC company recently launched here in the UK. Sanogenetics.com. Twice the price of Dante but early reports are positive people getting averages of 60x and higher within the promised turnaround. You get what you pay for I guess...

**Comment by anderspitman** [comment]
That said, we're working on a big update to our backend infrastructure, and master/gh-pages will stop working once we flip the switch, which will likely be in the next couple weeks.
