### ISSUE TITLE
Scalable axis on read coverage

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#52]
There are often times where there is a region with high coverage, so you can't distinguish much information across the genome/chromosome. If you're looking for evidence of a large SV, you're pretty much stumped. Here is an example:

<img width="913" alt="screen shot 2016-11-13 at 9 19 48 am" src="https://cloud.githubusercontent.com/assets/523111/20246314/5ed703ee-a982-11e6-9fe7-ee891b69c1a7.png">

I would like to rescale this, to remove the effect of the massive spike. As it stands, I really can't tell if there is anything interesting in this chromosome (and I have reason to believe that there might be).

**Comment by tonydisera** [comment]
Good call.  This is important to address.  I like the idea of a toggle or a threshold for scaling the density on the y-axis.

**Comment by chmille4** [comment]
Leaving out UX considerations for the moment, there seems two ways to do this

- (1) Let user zoom into region of X axis
  - Advantages
    - Can see more height (y axis) variation in the selected region
    - Can see more size (x axis) variation in the selected region
  - Disadvantages
    - Can not see whole chromosome at a glance
    - Resolution is limited on the X axis to ~16k points, so zoom will be limited
- (2) Let user change scale of Y axis
  - Advantages
    - Can see whole chromosome at a glance
    - Can see more height (y axis) variation when y scale is decreased
  - Disadvantages
    - Higher y peaks are cut off when y scale is decreased
    - Smaller events may still be hard to see since X axis is big

@AlistairNWard which seems like a better fit for what you need?

**Comment by AlistairNWard** [comment]
(2) seems the best. The issue is simply that when you have a really outsize
peak, the whole view is rendered useless. Scaling the y-axis would allow
the effect of the outliers to be removed. The higher peaks would be cut
off, but I don't see this as a disadvantage, since that was the goal in the
first place. Plus the user can zoom out again if they desire. Smaller
events will still be hard to see, but that's fine. We could implement
scaling on both at some point, but I would argue that once y-scaling is in,
the major problem is resolved.

**Comment by chmille4** [comment]
Would a logarithmic scale work? Could just add a toggle, which would be very easy

**Comment by AlistairNWard** [comment]
It might be. That was actually my first though, but even I thought it would
be best to give the user total control if possible. In the example, I'm not
sure how many orders of magnitude larger the outlier is, so I'm not totally
sure if, even, with a logarithmic scale, the remainder of the coverage
would be comparable. Maybe as a first solution, a logarithmic scale would
be sufficient, but I think more control is better in the end.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by chmille4** [comment]
Ok, I'll try a log scale first. If that is enough then we can keep things simpler, which is best. If it's still drowning out the smaller events then I'll add more control.

**Comment by AlistairNWard** [comment]
Long term, do you think that log scale is best, even if functional for this
case. If we're promoting exploratory research, should we not aim to provide
the most control possible to the user?


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by chmille4** [comment]
Always a trade of between more control/more complex UI and less control/simpler UI.  I think it's worth looking at log scale first before we jump to a more complex solution. Though in this case I have a feeling you are right and that we will end up with finer control on the y axis.

**Comment by AlistairNWard** [comment]
Either way, there's a good chance the log scale will tide us over for a
good long while.


Alistair Ward, PhD
Director, Research and Science
Department of Human Genetics
USTAR Center for Genetic Discovery
Eccles Institute of Human Genetics
University of Utah School of Medicine​
15 North 2030 East, Room 7140
Salt Lake City, UT 84112-5330

Co-founder, Frameshift labs, LLC

**Comment by AlistairNWard** [comment]
The log scale doesn't really solve the problem, so we can add this to the development in Phase II.
