### ISSUE TITLE
Numerical scale on read coverage

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#53]
Sorry to throw so many issues up! Would it be possible to put a numerical scale on the read coverage when showing individual chromosomes? Here is some context to why. I have been looking at coverage in H1K samples and finding some concerning results. I am finding not infrequent occurrences of very low coverage. For example, see the proband in this gene:

<img width="1384" alt="screen shot 2016-11-14 at 4 59 21 pm" src="https://cloud.githubusercontent.com/assets/523111/20284624/ea2dae52-aa8b-11e6-8a89-5120983551b9.png">

The coverage looks way off in the proband. One quick check is to then look and see if there is a large deletion spanning the gene. From gene.iobio, I know the gene coordinates, so I open bam.iobio and look in the correct chromosome, and I see this:

<img width="919" alt="screen shot 2016-11-14 at 4 59 39 pm" src="https://cloud.githubusercontent.com/assets/523111/20284667/1878b1b2-aa8c-11e6-83a9-4a037abcb8cf.png">

So, here you see why I want to remove the effect of the big spike to try and gauge if there is a deletion. Then, I want to look in the approximate region of the gene to see if I can see anything, but I have no guide as to where the gene is. A numerical scale on the x axis would thus be really useful. Looking at the read coverage distribution, there is clearly an issue with the coverage in this chromosome.

<img width="818" alt="screen shot 2016-11-14 at 4 59 35 pm" src="https://cloud.githubusercontent.com/assets/523111/20284731/5fcbe930-aa8c-11e6-967d-61f25f3fbb6b.png">

**Comment by chmille4** [comment]
yep, x scale was in the old bam.iobio but got lost in the shuffle in the new version. I'll add it.

**Comment by chmille4** [comment]
x scale added (0faab97fd616222091549ee1967b8d796a1fb2b8). It was actually there but had been turned white by an overzealous css style.
