### ISSUE TITLE
From Andrew - Show bam file name (or URL) in bam.iobio so that user knows which file he/she is working on.

### ISSUE THREAD

**Issue by tonydisera** [chmille4/bam.iobio.io#59]
Here is where the file is labeled in vcf.iobio:

<img width="823" alt="screen shot 2017-03-14 at 11 28 03 am" src="https://cloud.githubusercontent.com/assets/8420103/23913749/80f030d2-08a9-11e7-8bd5-2c328725c894.png">

**Comment by AlistairNWard** [comment]
Duplicate of #69
