### ISSUE TITLE
Label axes

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#66]
A number of people have not understood what the different graphics are showing. We should make sure that all axes are labelled.

**Comment by mjbowler** [comment]
What should the labels be for the various charts? Thanks!

**Comment by chmille4** [comment]
For Read Coverage distribution - x axis: Read Coverage; y axis: Frequency. Also add an X for the labels on the X axis e.g. (60X, 100X, etc)

For Fragment Length distribution - x axis: Fragment Length; y axis: Frequency 

For Read Length distribution - x axis: Read Length; y axis: Frequency 

For Mapping Quality distribution - x axis: Mapping Quality; y axis: Frequency 

For Base Quality distribution - x axis: Base Quality; y axis: Frequency

**Comment by mjbowler** [comment]
I likely could have guessed those... Thanks though!
