### ISSUE TITLE
Include select to zoom statement

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#71]
e.g. in multibam, there is a statement that you can zoom in on a region.

**Comment by mjbowler** [comment]
@AlistairNWard , do you have a picture of this?

**Comment by chmille4** [comment]
I'm pretty sure Al is referring to the text here (red arrow below) which informs the user they can zoom by selecting a region.

<img width="1256" alt="screen shot 2018-02-05 at 4 02 28 pm" src="https://user-images.githubusercontent.com/88370/35828594-1c5c18ce-0a8e-11e8-8f7f-0a844c8cabc1.png">

**Comment by AlistairNWard** [comment]
Exactly. The read coverage distribution chart in bam.iobio can be zoomed into, but there is no indication to the user that this is the case.

<img width="826" alt="screen shot 2018-02-06 at 5 44 40 am" src="https://user-images.githubusercontent.com/523111/35855397-18a2d5e2-0b01-11e8-95cd-ed0483ae44dc.png">

**Comment by mjbowler** [comment]
This is what I have... 
![histo.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5a68fe5f7453d30014ef4f07/125516c66e82c728ace21e0d46e09d89378dc1e5cdf9ad4cae58f3806b1c65267107fa2a23dde72de8172d505b5f4eab145f5c4dfdfa8039baa47e21d40854b088270a36d43703adb1881eba00bd298f4f87b6b58a49c6fa70.png)

**Comment by chmille4** [comment]
That works. You can close when merged.

**Comment by chmille4** [comment]
Actually you can close as soon as the commit is pushed to your branch. Easier to keep track of that way.
