### ISSUE TITLE
Chromosomes are messed up for GRCh38

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#88]
Try this file:

https://s3.amazonaws.com/iobio/samples/bam/NA12877.exome.bam

1. We get a warning about too many references, but didn't lose any functionality. Maybe it makes sense to make it clear that there are more reference sequences than shown, but this warning should block the view.

2. The reference id colour bar is behind other cards.

<img width="1489" alt="screen shot 2018-05-15 at 4 21 03 pm" src="https://user-images.githubusercontent.com/523111/40081583-6854f342-585c-11e8-808f-7d286bcf3af6.png">

**Comment by anderspitman** [comment]
@AlistairNWard I don't think this is still happening on the latest vue branch. I also made some changes in #103 that affect the "Too many references" message. I don't think it is currently working properly, unless I misunderstand its purpose.
