### ISSUE TITLE
Invalid BAM path

### ISSUE THREAD

**Issue by AlistairNWard** [chmille4/bam.iobio.io#91]
If you enter a URL that doesn't exist, the app hangs. I just typed bob as the URL and old bam just sits Initializing data. New bam just has a blank page

**Comment by anderspitman** [comment]
@AlistairNWard this looks pretty easy to fix. I'm assuming we want behavior similar to the user entering a blank URL, ie a popup telling them they done goofed?

**Comment by AlistairNWard** [comment]
Exactly. Nothing fancy, just something so the user doesn't stare at their screen all day wondering what's gone wrong!

**Comment by anderspitman** [comment]
I guess it could actually be more involved, depending on how in depth we want to go. If we just want to handle simple cases such as "bob" where it's obviously not a valid URL, that should be pretty straight forward. However, if they provide a valid URL that doesn't point to a valid location, we'll need to send a request and see if there's anything there.

**Comment by anderspitman** [comment]
I work on handling both.

**Comment by tonydisera** [comment]
Agreed.  I'm not sure why this is commented out.

**Comment by anderspitman** [comment]
Fixed in #96
